services:
  echo_bot:
    container_name: echo_bot_container
    image: echo_bot
    build: 
      context: .
    environment:
      - BOT_TOKEN:${BOT_TOKEN}
    depends_on:
      - bot_db
  
  bot_db:
    container_name: postgres_bot_container
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_NAME}
      - PGDATA=${PG_DATA}
    ports:
      - ${PG_PORT}:${PG_PORT}
    expose:
      - ${PG_PORT}
    volumes:
      - postgres_data:/data/postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    profiles:
      - "dev"
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - echo_bot

volumes:
  postgres_data:
  pgadmin_data:
